name: Build EXE

on:
  push:
    branches:
      - V1
  pull_request:
    branches:
      - V1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller openpyxl
          

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --add-data "languages.json;." --name "CreateGroupsTempTPRO" main_runner.py

      - name: Verify Output
        run: dir dist

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist\CreateGroupsTempTPRO.exe
