name: Build Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Run Scripts (Main Runner)
      run: |
        python main_runner.py  # This will run the orchestrating script, skipping the GUI in CI

    - name: Build Executable
      run: pyinstaller --onefile --windowed --name=CreateTproGroupImportTemplate --add-data "languages.json;." --add-data "language_viewer.py;." main_runner.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CreateTproGroupImportTemplate_windows
        path: dist/CreateTproGroupImportTemplate.exe
