name: Build Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt  # Install any additional dependencies if you have

    - name: Run Scripts (Main Runner)
      run: |
        python main_runner.py  # This runs your orchestrating script that handles the logic

    - name: Build Executable
      run: pyinstaller --onefile --windowed --name=CreateTproGroupImportTemplate --add-data "languages.json;." --add-data "language_viewer.py;." main_runner.py
      # The `--add-data` option ensures language_viewer.py and languages.json are bundled

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CreateTproGroupImportTemplate_windows
        path: dist/CreateTproGroupImportTemplate.exe
