name: Build Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile --windowed test.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test_executable_windows
        path: dist/test.exe

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile --windowed test.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test_executable_linux
        path: dist/test
